include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  language:
    strict-inference: true
    strict-raw-types: true
    strict-casts: true

linter:
  rules:
    public_member_api_docs: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_dynamic_calls: true
