name: app_management
description: "Production-grade starter template with Riverpod and go_router."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_riverpod: 3.0.0
  go_router: 14.2.7
  dio: 5.4.3+1
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter_secure_storage: 9.2.2
  connectivity_plus: 6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: 6.0.0
  mocktail: 1.0.3

flutter:
  uses-material-design: true
